import os

base = os.path.expanduser('~/projects/malloc-training/')

curriculum = """# CURRICULUM
# Generated by: Session 1 - May 25 2026
# Course: CMU 15-213
# Lab: L0 C Programming Lab
# Total projects planned: 30
# Last updated: 2026-05-25

# PHASE 1
# Goal: Own memory pointers and structs at the byte level
# Prerequisites: None. Starting from zero.

PROJECT 1
  Name     : Bytes and Variables
  Concept  : A variable is a named region of bytes at a real address in RAM
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student thinks in variable names not addresses
  Builds on: Nothing
  Unlocks  : Everything. No mental model works without this.

PROJECT 2
  Name     : Addresses and printf
  Concept  : Every variable has an address you can read with &
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student does not know variables live at real locations
  Builds on: Project 1
  Unlocks  : Project 3

PROJECT 3
  Name     : What a Pointer Actually Is
  Concept  : A pointer is an integer that holds an address
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student treats pointers as magical not as integers
  Builds on: Project 2
  Unlocks  : Project 4

PROJECT 4
  Name     : Dereferencing
  Concept  : The * operator follows the address and touches the bytes
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Confusing pointer value with value at pointed address
  Builds on: Project 3
  Unlocks  : Project 5

PROJECT 5
  Name     : Pointer Assignment vs Value Assignment
  Concept  : p = q moves the address. *p = *q moves the value
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student conflates changing pointer with changing data
  Builds on: Project 4
  Unlocks  : Project 6

PROJECT 6
  Name     : Structs as Byte Blocks
  Concept  : A struct is a contiguous region of bytes with named offsets
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student thinks struct fields are separate variables
  Builds on: Project 5
  Unlocks  : Project 7

PROJECT 7
  Name     : Pointers to Structs and the Arrow Operator
  Concept  : p->field is exactly (*p).field nothing more
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Arrow operator feels magical instead of mechanical
  Builds on: Project 6
  Unlocks  : Project 8

PROJECT 8
  Name     : Strings in C
  Concept  : A string is not a type it is a convention about bytes
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student treats strings as values not as byte arrays
  Builds on: Project 7
  Unlocks  : Project 9

PROJECT 9
  Name     : strlen and the Null Terminator
  Concept  : strlen counts until it hits zero not including zero
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Off-by-one on string allocation
  Builds on: Project 8
  Unlocks  : Project 10

PROJECT 10
  Name     : malloc
  Concept  : malloc returns a pointer to n bytes or NULL on failure
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student does not check NULL return from malloc
  Builds on: Project 9
  Unlocks  : Project 11

PROJECT 11
  Name     : free
  Concept  : free marks bytes as available it does not zero them
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student thinks free erases memory
  Builds on: Project 10
  Unlocks  : Project 12

PROJECT 12
  Name     : malloc and free Must Balance
  Concept  : Every malloc needs exactly one free no more no less
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Leaks and double-frees both come from imbalance
  Builds on: Project 11
  Unlocks  : Project 13

PROJECT 13
  Name     : NULL Pointer
  Concept  : NULL is address zero dereferencing it is always wrong
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student does not guard against NULL before dereferencing
  Builds on: Project 12
  Unlocks  : Project 14

PROJECT 14
  Name     : Copying Strings with malloc and strcpy
  Concept  : To own a string you must allocate space and copy bytes
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student stores pointer to caller string instead of copy
  Builds on: Project 13
  Unlocks  : Project 15

PROJECT 15
  Name     : Typedef and Struct Aliases
  Concept  : typedef gives a struct a usable name no new behavior
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student confused by list_ele_t vs struct list_ele
  Builds on: Project 14
  Unlocks  : Project 16

PROJECT 16
  Name     : Linked List One Node by Hand
  Concept  : A node is a struct with a pointer to the next node
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student cannot build the physical picture of a linked node
  Builds on: Project 15
  Unlocks  : Project 17

PROJECT 17
  Name     : Linking Two Nodes
  Concept  : Setting next pointer connects two heap-allocated nodes
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student does not see that next is just an address in a field
  Builds on: Project 16
  Unlocks  : Project 18

PROJECT 18
  Name     : Traversing a Linked List
  Concept  : A loop follows next pointers until NULL never recurse
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student writes recursive traversal stack overflow at 1M nodes
  Builds on: Project 17
  Unlocks  : Project 19

PROJECT 19
  Name     : sizeof
  Concept  : sizeof gives compile-time byte count not runtime length
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : sizeof pointer vs sizeof pointee confusion
  Builds on: Project 18
  Unlocks  : Project 20

PROJECT 20
  Name     : The malloc sizeof Pattern
  Concept  : Allocating a struct always uses sizeof that struct
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 1
  Gap      : Student hardcodes sizes instead of using sizeof
  Builds on: Project 19
  Unlocks  : Phase 2

# PHASE 2
# Goal: Implement all seven queue functions correctly
# Prerequisites: Phase 1 complete

PROJECT 21
  Name     : queue_new
  Concept  : Creating a queue means allocating a queue_t and zeroing fields
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 2
  Gap      : Student does not initialize fields after malloc
  Builds on: Project 20
  Unlocks  : Project 22

PROJECT 22
  Name     : queue_free
  Concept  : Free nodes before freeing the queue struct itself
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 2
  Gap      : Student frees queue_t first loses pointer to nodes
  Builds on: Project 21
  Unlocks  : Project 23

PROJECT 23
  Name     : queue_insert_head
  Concept  : Allocate node copy string point node to old head update head
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 2
  Gap      : Student updates head before saving old head list lost
  Builds on: Project 22
  Unlocks  : Project 24

PROJECT 24
  Name     : queue_insert_tail
  Concept  : tail pointer makes append O(1) update tail on every insert
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 2
  Gap      : Student walks list to find tail O(n) fails at 1M elements
  Builds on: Project 23
  Unlocks  : Project 25

PROJECT 25
  Name     : queue_size
  Concept  : Return the stored size field never traverse the list
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 2
  Gap      : Student counts nodes O(n) fails performance test
  Builds on: Project 24
  Unlocks  : Project 26

PROJECT 26
  Name     : queue_remove_head
  Concept  : Save next copy string out free node update head
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 2
  Gap      : Student frees node before copying string out of it
  Builds on: Project 25
  Unlocks  : Project 27

PROJECT 27
  Name     : queue_reverse
  Concept  : Walk list once reverse each next pointer swap head and tail
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 2
  Gap      : Student allocates new nodes violates lab constraint
  Builds on: Project 26
  Unlocks  : Project 28

PROJECT 28
  Name     : Edge Cases NULL Queue and Empty Queue
  Concept  : NULL queue and empty queue are different and both must work
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 2
  Gap      : Student handles one but not the other crashes on traces
  Builds on: Project 27
  Unlocks  : Project 29

PROJECT 29
  Name     : AddressSanitizer
  Concept  : ASan reports tell you exact file line and violation type
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 2
  Gap      : Student cannot read a stack trace fixes wrong location
  Builds on: Project 28
  Unlocks  : Project 30

PROJECT 30
  Name     : Full Trace Run
  Concept  : driver.py is the ground truth all 100 points
  Lab      : L0 C Programming Lab
  Course   : CMU 15-213
  Phase    : 2
  Gap      : Student passes some traces and cannot diagnose failures
  Builds on: Project 29
  Unlocks  : Phase 3
"""

reasoning = """# CURRICULUM REASONING
# Generated by: Session 1 - May 25 2026
# Course: CMU 15-213
# Lab: L0 C Programming Lab
# ═══════════════════════════════════════════════════════

NEXT PROJECT: 2
  Why now          : Project 1 confirmed student thinks in variable names not addresses. The & operator was confused with pass-by-reference. Must solidify that addresses are real values before introducing pointers.
  Weakness targeted: Address vs value confusion appeared immediately in Project 1
  Teaching angle   : An address is a value you can store and pass around. Not magic. Not special syntax.
  Analogy          : House address written on a piece of paper. The paper holds the address. The house holds the contents.
  Watch for        : Student may still conflate & with pass-by-reference from other languages.

NEXT PROJECT: 3
  Why now          : After Project 2 student knows & gives an address. Now must see that an address can be stored in a variable. That variable is a pointer. Nothing magical.
  Weakness targeted: Pointers feel magical. Student will treat them as special. They are integers.
  Teaching angle   : A pointer is just an integer. Print it with %p and you see a number.
  Analogy          : A pointer is a piece of paper with a house address written on it.
  Watch for        : Student may think pointer type matters for what it IS rather than how it is used.

NEXT PROJECT: 4
  Why now          : Student knows a pointer holds an address. Now must see that * follows that address to the actual bytes. This is the operation everything else depends on.
  Weakness targeted: Confusing the pointer itself with what it points to.
  Teaching angle   : * means go to that address and read or write the bytes there.
  Analogy          : You have a paper with an address. * means physically go to that house and open the door.
  Watch for        : Student writing *p when they mean p or p when they mean *p.

NEXT PROJECT: 5
  Why now          : Student can dereference. Now must see the difference between moving the pointer and moving the value. This distinction breaks queue_insert_head if not owned.
  Weakness targeted: Conflating pointer reassignment with data mutation.
  Teaching angle   : Two operations that look similar but do completely different things.
  Analogy          : Changing which house your paper points to vs changing what is inside the house.
  Watch for        : Student reassigning head pointer and losing the old list.

NEXT PROJECT: 6
  Why now          : Student owns pointers. Now must see structs as byte blocks not abstract containers. queue_t and list_ele_t are structs. Cannot implement queue without this.
  Weakness targeted: Student thinks struct fields are separate variables floating in space.
  Teaching angle   : A struct is one contiguous block of bytes. Fields are named offsets into that block.
  Analogy          : A form with labeled boxes. All boxes are printed on one sheet of paper.
  Watch for        : Student surprised that sizeof struct includes all fields.

NEXT PROJECT: 7
  Why now          : Student knows structs. Now must own the arrow operator because every queue function uses it constantly. Arrow must feel mechanical not magical.
  Weakness targeted: Arrow operator feels like special syntax. It is not.
  Teaching angle   : p->field is (*p).field. Two operations you already know combined.
  Analogy          : Go to the address on the paper. Open the door. Look in the labeled box.
  Watch for        : Student using dot when they have a pointer. Using arrow when they have a value.

NEXT PROJECT: 8
  Why now          : Student owns structs and pointers. Queue stores char* strings. Must understand what a string physically is before allocating or copying one.
  Weakness targeted: Student treats strings as values not byte arrays.
  Teaching angle   : A string is an array of bytes ending in zero. Nothing more.
  Analogy          : A row of mailboxes. Each holds one character. Last one always holds zero.
  Watch for        : Student forgetting null terminator exists. Off-by-one on allocation.

NEXT PROJECT: 9
  Why now          : Student knows strings are byte arrays. Now must own strlen because malloc needs exact byte count. Off-by-one here causes buffer overflow that ASan catches.
  Weakness targeted: Off-by-one on string allocation. Most common bug in queue_insert_head.
  Teaching angle   : strlen returns length without the zero. malloc needs length plus one.
  Analogy          : strlen counts the letters in the word. malloc needs space for letters plus the period at the end.
  Watch for        : malloc(strlen(s)) instead of malloc(strlen(s) + 1). Will corrupt memory silently.

NEXT PROJECT: 10
  Why now          : Student knows how many bytes to request. Now must own malloc itself. Every queue node allocation uses malloc. NULL check is not optional.
  Weakness targeted: Student does not check NULL return from malloc.
  Teaching angle   : malloc can fail. When it fails it returns NULL. Dereferencing NULL crashes.
  Analogy          : Asking a bank for a loan. Bank might say no. You must check before spending.
  Watch for        : Missing NULL check after malloc in queue functions.

NEXT PROJECT: 11
  Why now          : Student can allocate. Must now own free. Every queue_free and queue_remove_head calls free. Misunderstanding free causes double-free and use-after-free.
  Weakness targeted: Student thinks free erases memory or makes it safe to read.
  Teaching angle   : free tells the system this memory is available again. The bytes are still there until overwritten.
  Analogy          : Checking out of a hotel room. Your stuff might still be there but the room belongs to someone else now.
  Watch for        : Student reading from pointer after free. Student calling free twice on same pointer.

NEXT PROJECT: 12
  Why now          : Student owns malloc and free separately. Must now see they must balance. One malloc one free. This is the rule ASan enforces. Leaks and double-frees both break this.
  Weakness targeted: Imbalanced malloc and free. Source of most memory bugs in the queue.
  Teaching angle   : Draw the balance. Every malloc gets a matching free. Count them.
  Analogy          : Every time you borrow something you must return it exactly once.
  Watch for        : queue_free missing free for string inside each node.

NEXT PROJECT: 13
  Why now          : Student knows malloc can return NULL. Must now own what NULL actually is and why dereferencing it always crashes. Every queue function checks for NULL queue.
  Weakness targeted: Student does not guard against NULL before dereferencing.
  Teaching angle   : NULL is address zero. The OS protects address zero. Touching it crashes.
  Analogy          : Address zero is a locked building. Going there gets you arrested immediately.
  Watch for        : Missing NULL check at start of every queue function.

NEXT PROJECT: 14
  Why now          : All tools are owned. Student can now implement string copying which is what queue_insert_head and queue_insert_tail actually do. This is the first real composition.
  Weakness targeted: Student stores pointer to caller string instead of making own copy.
  Teaching angle   : You do not own memory you did not allocate. Always copy strings you need to keep.
  Analogy          : Taking a photo of someone elses document instead of photocopying it. When they shred it you lose the information.
  Watch for        : Storing s directly instead of allocating and copying.

NEXT PROJECT: 15
  Why now          : Student is about to read queue.h which uses typedef extensively. Must understand typedef before reading the actual lab structs or confusion blocks progress.
  Weakness targeted: Student confused by list_ele_t vs struct list_ele.
  Teaching angle   : typedef is just a rename. No new behavior. list_ele_t is struct list_ele.
  Analogy          : A nickname. The person is the same. The name is shorter.
  Watch for        : Student thinking typedef creates a new type with different behavior.

NEXT PROJECT: 16
  Why now          : All foundations owned. Student now builds one linked list node by hand from scratch. This makes the abstract data structure physically real before implementing the queue.
  Weakness targeted: Student cannot picture what a node actually is in memory.
  Teaching angle   : A node is just a struct on the heap with a value and a next pointer.
  Analogy          : A box with a string inside and an arrow painted on the outside pointing to the next box.
  Watch for        : Student confused about why next is a pointer not a struct.

NEXT PROJECT: 17
  Why now          : Student has one node. Must now link two nodes together and see the chain physically. This is the exact operation queue_insert_head performs.
  Weakness targeted: Student does not see that linking is just assigning an address to a field.
  Teaching angle   : next is just a field. Setting it to another node address is just assignment.
  Analogy          : Drawing an arrow from one box to another. The arrow is the next pointer.
  Watch for        : Student allocating new memory when they should just be setting a pointer.

NEXT PROJECT: 18
  Why now          : Student can link nodes. Must now traverse a list with a loop. queue_free and queue_reverse both traverse. Recursive traversal stack-overflows at 1M nodes.
  Weakness targeted: Student writes recursive traversal. Forbidden at 1M elements.
  Teaching angle   : A cursor pointer walks the chain. While cursor is not NULL advance it.
  Analogy          : Walking a chain of connected rooms. Enter room. Note next door. Move through it. Repeat.
  Watch for        : Any recursive function that touches list nodes.

NEXT PROJECT: 19
  Why now          : Student is about to write malloc(sizeof(list_ele_t)). Must own sizeof first. sizeof pointer vs sizeof pointee is a reliable misconception.
  Weakness targeted: sizeof pointer vs sizeof pointee confusion.
  Teaching angle   : sizeof(int*) is 8. sizeof(int) is 4. The pointer and what it points to are different sizes.
  Analogy          : The address of a house fits on one line. The house itself is much larger.
  Watch for        : malloc(sizeof(list_ele_t*)) instead of malloc(sizeof(list_ele_t)).

NEXT PROJECT: 20
  Why now          : Student owns sizeof. Now must own the malloc(sizeof(T)) pattern which every queue function uses. This is the last foundation piece before Phase 2 implementation begins.
  Weakness targeted: Student hardcodes struct sizes or uses wrong sizeof argument.
  Teaching angle   : Always malloc(sizeof(the_struct_not_the_pointer)).
  Analogy          : Order a box big enough to fit the object not big enough to fit the label.
  Watch for        : Any hardcoded size in a malloc call.
"""

with open(base + 'CURRICULUM.md', 'w') as f:
    f.write(curriculum)
print('CURRICULUM.md written.')

with open(base + 'CURRICULUM_REASONING.md', 'w') as f:
    f.write(reasoning)
print('CURRICULUM_REASONING.md written.')
